# Generated by Django 3.2.15 on 2022-10-01 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsrGender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender_name', models.CharField(max_length=20)),
                ('gender_initial', models.CharField(max_length=1)),
                ('gender_detail', models.CharField(max_length=80)),
                ('gender_code', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'usr_gender',
            },
        ),
        migrations.CreateModel(
            name='UsrUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('username', models.CharField(max_length=20)),
                ('user_code', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_no', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=20)),
                ('profile_image', models.ImageField(null=True, upload_to='images/profile_images/')),
                ('designation', models.CharField(max_length=125)),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.usrgender')),
            ],
            options={
                'db_table': 'usr_user',
            },
        ),
    ]
