# Generated by Django 3.2.15 on 2022-09-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usruser',
            name='password',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usruser',
            name='mobile_no',
            field=models.IntegerField(max_length=15),
        ),
    ]
