# Generated by Django 3.2.15 on 2022-09-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220923_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usruser',
            name='password',
            field=models.CharField(max_length=20),
        ),
    ]
