# Generated by Django 3.2.15 on 2022-09-23 11:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_usruser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usruser',
            name='mobile_no',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(0)]),
        ),
    ]
