# Generated by Django 3.2.15 on 2022-09-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_usruser_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usruser',
            name='mobile_no',
            field=models.CharField(max_length=15),
        ),
    ]
